### ISSUE TITLE
ConvPoolOpBase is not in operators catalogue

### ISSUE THREAD

**Issue by ezyang** [facebookarchive/caffe2#1011]
Many operators reference ConvPoolOpBase as a parent class which defines shared parameters in  https://caffe2.ai/docs/operators-catalogue.html

However, ConvPoolOpBase is not mentioned anywhere in the documentation, which means it is not possible to tell what exactly these parameters are without actually source diving.

**Comment by Yangqing** [comment]
Ah this is because these parameters are being shared by conv, pool and a bunch of other operators - hence we have a base class. Documenting the parameters shall be done in the schema proper, which is an action item in the IR part :)

**Comment by CarlosYeverino** [comment]
Hello @Yangqing ,

can you please provide an example showing how to set the ConvPoolOpBase operator to be able to use the MaxPool and Conv operators for network modelling? It would be nice to have a reference for it since I haven't found any example.

I am interested in modelling networks using only operators and not any helper functions.
