### ISSUE TITLE
What is common_world??

### ISSUE THREAD

**Issue by ing907** [facebookarchive/caffe2#1026]
Hello I'm the man who wants to know how CAFFE2 work in C++ side.
Nowadays, I'm trying to understand how the distributed learning works.
I recently run Resnet50_trainer.py and noticed that CAFFE2 uses allreduce operator rather than nccl allreduce as a operator to gradient aggregation among multi workers.

I would like to know what is the comm_world, One of the input of allreduce operator.
I already know it is generated with **CreateCommonWorld** operator called via `workspace.RunNetOnce(train_model.param_init_net)` but don't know the role and the meaning of common world in allreduce operator.

I also want to know why the `train_model.net.Proto` has `num_workers: 12` even I used 1GPU per each machine.

**Comment by pietern** [comment]
The common world encapsulates the state needed to perform the inter-machine collective. You can think of this as the TCP connections and information about process rank. This common world can be reused across multiple collectives. They are reused in Caffe2 in a way that they don't overlap, which is why we create more than 1 of them. The question about 12 workers is related: reduction of gradients of multiple layers can happen in parallel. There is no data dependency for computing the gradient and updating the weights between layers, so this can be done in parallel for multiple layers.
