### ISSUE TITLE
the Caffe2 library does not seem to be linked with whole-static library option

### ISSUE THREAD

**Issue by aligoglos** [facebookarchive/caffe2#1370]
i successfully compile caffe2 lib with visual studio 2015 as static library. but when add .lib's into my c++ project and want to run my program this run time error occur :
`[F operator.h:644] You might have made a build error: the Caffe2 library does not seem to be linked with whole-static library option. To do so, use -Wl,-force_load (clang) or -Wl,--whole-archive (gcc) to link the Caffe2 library.`

i set DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS in CMAKE when want create solution but not solve.

**Comment by Yangqing** [comment]
Windows uses -WHOLEARCHIVE - could you give that a shot?

https://msdn.microsoft.com/en-us/library/mt732963.aspx

**Comment by Yangqing** [comment]
Also, this macro might be helpful:

https://github.com/caffe2/caffe2/blob/f2cf8933fc8c04f149ea27f30381517df358c1b5/cmake/Utils.cmake#L173-L185

**Comment by aligoglos** [comment]
i try very different way but not work. finally i find this [problem ](https://github.com/tensorflow/tensorflow/issues/6396) in tensotflow,  and it's solution work for caffe2.
you just need attach all .obj files to your solution and compile it.

**Comment by badtiger8013** [comment]
@aligoglos Could you show how to do that " attach all .obj files to your solution"? sorry ,I have been troubled by this problem for weeeeeks!

**Comment by aligoglos** [comment]
hi you should just use 'Add -> Existing items' to add all .obj files in
your solution.

**Comment by badtiger8013** [comment]
@aligoglos you mean : thanks for the reply. you mean, for each project in the solution , add the corresponding .obj file and then build ALL_BUILD？

**Comment by aligoglos** [comment]
just for that project, you want add caffe2 libraries.
solution of your test project.

**Comment by CarlosYeverino** [comment]
Hi @aligoglos ,

I successfully built Caffe2 from source on windows 10. Now, I would like to use caffe2 libraries in Visual Studio 2015 to write C++ programs. **How should I add the libraries and from what path in order to be able to include the libraries as below?**
```
#include "caffe2/core/common.h"
#include "caffe2/utils/proto_utils.h"
#include "caffe2/core/workspace.h"
#include "caffe2/core/tensor.h"
#include "caffe2/core/init.h"
```

Should I add only these libraries?

![image](https://user-images.githubusercontent.com/25825048/44961661-2ed9cd80-af15-11e8-8621-d99fdc1bfa9d.png)

I followed this guide https://caffe2.ai/docs/cplusplus_tutorial.html . I added the following directories in Visual Studio:
D:\Yeverino\git_projects\pytorch\build\lib\Release
D:\Yeverino\git_projects\pytorch\build\caffe2\proto\Caffe2_PROTO.dir\Release
D:\Yeverino\git_projects\pytorch\caffe2\cuda_rtc\core
D:\Yeverino\git_projects\pytorch\caffe2\proto
D:\Yeverino\git_projects\pytorch\build
D:\Yeverino\git_projects\pytorch\build\caffe2

![image](https://user-images.githubusercontent.com/25825048/44974444-f6131600-af5f-11e8-9437-2ab1f32f736f.png)

However, I got errors like below when I tried to include #include <blob.h> in a project:
`Error	C1083	Cannot open include file: 'caffe2/core/common.h': No such file or directory	ConsoleApplication1	D:\Yeverino\git_projects\pytorch\caffe2\cuda_rtc\core\blob.h	11	`

Once I changed `#include "caffe2/core/blob_serializer_base.h"` to `#include "blob_serializer_base.h"`, error was fixed and other similar errors were detected due to the prefix "caffe2/$package/" in the includes. I really want to avoid renaming all includes.

**Comment by aligoglos** [comment]
yes you just add this libs and if you get this error :
the Caffe2 library does not seem to be linked with whole-static library
option
you must add .obj into your project also.
