### ISSUE TITLE
Compile error with caffe2 git master

### ISSUE THREAD

**Issue by dbermond** [facebookarchive/caffe2#1459]
I'm getting the following error when trying to compile caffe2 git master:

https://bpaste.net/show/4e7fab60e7fd

A git bisect shows that this is being caused by commit 0c50143fef8f956225ec3f2b24dfd94dd514519f.

cmake configuration: https://bpaste.net/show/ec6f1fc8d93d

**System information:**
**OS:** Arch Linux x86_64
**caffe2:** git master
**Compiler:** gcc 6.4.1
**CUDA:** 9.0.176

**Comment by Yangqing** [comment]
@bddppq Do you mind taking a look?

**Comment by otaj** [comment]
@bddppq Hi, is there any update? Master is still uncompilable at the moment.

**Comment by pietern** [comment]
No update yet. Some progress on monitoring build problems: we have been working on a Jenkins setup where we monitor a dozen or so build environments (mixture of Python versions, compilers, Ubuntu/CentOS, and CUDA version). The output @dbermond pastes hints at a combination of CUDA 9 and GCC 6.4 being the problem here. We monitor CUDA 9 builds with GCC 5, and CPU-only builds for GCC 6.3.0, but not yet CUDA 9 with GCC 6.

**Comment by ppwwyyxx** [comment]
https://devtalk.nvidia.com/default/topic/1028112/cuda-setup-and-installation/nvcc-bug-related-to-gcc-6-lt-tuple-gt-header-/post/5234434/#5234434

Seems to be nvcc bug.

**Comment by pjh5** [comment]
This will now be tracked in #1636
