### ISSUE TITLE
OSX Build Error

### ISSUE THREAD

**Issue by MabinogiX** [facebookarchive/caffe2#1684]
I have built caffe2 successfully on my macbook pro. Then I wanted to reinstall it in another path and I removed `caffe` and `caffe2` in `/usr/local/`. Also I renamed the directory which contains caffe2 source file.
Then I used the command to build caffe2 again:
```
mkdir build && cd build
cmake -DUSE_CUDA=OFF -DCMAKE_INSTALL_PREFIX:PATH=~/caffe2/ ..
sudo make install
```
Then there is an error:
```
[  7%] Building CXX object caffe/proto/CMakeFiles/Caffe_PROTO.dir/caffe.pb.cc.o
In file included from ~/caffe2-source/caffe2/build/caffe/proto/caffe.pb.cc:5:
~/caffe2-source/caffe2/build/caffe/proto/caffe.pb.h:17:2: error: This file was generated by
      an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
~/caffe2-source/caffe2/build/caffe/proto/caffe.pb.h:18:2: error: incompatible with your
      Protocol Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
~/caffe2-source/caffe2/build/caffe/proto/caffe.pb.h:19:2: error: regenerate this file with a
      newer version of protoc.
```
I removed the whole `build` folder and tried to build it again with the command:
```
mkdir build && cd build
cmake -DUSE_CUDA=OFF  ..
sudo make install
```
It also failed.
The version of protoc is 3.2.0 and I have built caffe2 successfully yesterday, how this happened?

**Comment by MabinogiX** [comment]
I have tried `brew install protobuf` && `pip install protobuf`, it did not work.
I have run diagnose_protobuf.py script, it said `All looks good.`.
I have run `scripts/build_local.sh` directly. There is the same error:
```
[  2%] Building CXX object caffe/proto/CMakeFiles/Caffe_PROTO.dir/caffe.pb.cc.o
Scanning dependencies of target Caffe2_PROTO
[  2%] Building CXX object caffe2/proto/CMakeFiles/Caffe2_PROTO.dir/caffe2.pb.cc.o
In file included from ~/caffe2-source/caffe2/build/caffe/proto/caffe.pb.cc:5:
~/caffe2-source/caffe2/build/caffe/proto/caffe.pb.h:17:2: error: This
      file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
~/caffe2-source/caffe2/build/caffe/proto/caffe.pb.h:18:2: error: 
      incompatible with your Protocol Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
~/caffe2-source/caffe2/build/caffe/proto/caffe.pb.h:19:2: error: 
      regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
```

**Comment by dingyuguo** [comment]
the same question I meet , I use Anaconda to configure my environment  ,and I try to download the 2.6.0 version of protobuf ,but I can't modify CMakelists.txt to change the path of the protobuf complier ,so it doesn't work yet.

**Comment by pjh5** [comment]
Can you run
`which protoc
protoc --version
find /usr -name libprotobuf* 2>/dev/null
find ~ -name libprotobuf* 2>/dev/null
`

CMake will prefer the protobuf under /usr/local (which is installed by brew) over other protobufs, even when installing in anaconda environments. See https://github.com/caffe2/caffe2/issues/654 . If you don't want to use the protobuf under /usr/local, the best thing to do is uninstall it. If you can, uninstalling all but one protobuf on your machine is the safest thing to do. 
diagnose_protobuf.py should be changed to check for this.

**Comment by MabinogiX** [comment]
The output is:
```
~/anaconda2/bin/protoc
~/anaconda2/bin/protoc
/usr/bin/find
/usr/bin/find
```
I will try the solutions in #654

**Comment by MabinogiX** [comment]
I thought I know what happened now. There are several versions of protoc on my computer:
```
/usr/local/bin/protoc    version 3.4.0
/usr/local/Cellar/protobuf/3.5.1/bin/protoc   version 3.5.1
~/anaconda2/pkgs/libprotobuf-3.2.0-0/bin/protoc   version 3.2.0
```

**Comment by MabinogiX** [comment]
When I use command:
```
cmake -DUSE_CUDA=OFF ..
```
It has some warnings about protoc:
```
CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindProtobuf.cmake:455 (message):
  Protobuf compiler version 3.2.0 doesn't match library version 3.4.0

-- Found Protobuf: /usr/local/lib/libprotobuf.a (found version "3.4.0") 
-- Using protobuf compiler ~/anaconda2/bin/protoc
```

I don't know where the protoc in `/usr/local/bin/protoc` comes from. I have unintalled protoc in brew and pip. There should be only one version of protoc in `conda`.
By the way, the version of protoc in `pip` and `brew` is v3.5.1 and the version of protoc in `conda` is v3.2.1

**Comment by pjh5** [comment]
Can you also try uninstalling from conda and installing again?

If you want to make sure you've uninstalled protobuf everywhere, you can manually delete all protobuf files that show up from
`
find / -name *protobuf* 2>/dev/null
`
(don't just pipe that into `rm`, but only delete things that are libproto* or under a protobuf folder)

**Comment by dingyuguo** [comment]
The problem is solved! 

## the problem I met:
 [the message I used is above] 
`[  7%] Building CXX object caffe/proto/CMakeFiles/Caffe_PROTO.dir/caffe.pb.cc.o
In file included from ~/caffe2-source/caffe2/build/caffe/proto/caffe.pb.cc:5:
~/caffe2-source/caffe2/build/caffe/proto/caffe.pb.h:17:2: error: This file was generated by
      an **older** version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
~/caffe2-source/caffe2/build/caffe/proto/caffe.pb.h:18:2: error: incompatible with your
      Protocol Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
~/caffe2-source/caffe2/build/caffe/proto/caffe.pb.h:19:2: error: regenerate this file with a
      newer version of protoc.`

# solution:
1:If you used Anaconda to configure your environment,You should remove all the dependence of protobuf which installed by the command `brew install protobuf`, /usr/local/include/protobuf/* /usr/local/bin/protoc, /usr/local/lib/libproto* and so on; 
2:And installed the 3.1.0 or 3.2.0 version of protobuf by  the command `conda install protobuf=3.2.0`,then remove build direction used the command `sudo rm -rf build`,and then `mkdir build && cd build && cmake .. && sudo make install `, And you will see the question is solved !
# By the way
 1:then I met the problem of "Eigen ",It says some include files can't find;That's because I had installed Eigen3 without "unsupported folder"  in /usr/locla/include/eigne3  on my computer before ;and caffe 2 CMakelist.txt just find the default Eigen 3 path , so the error occurs;
2: I change the `vim  cmake/Dependencies.cmake + 241`,

>  find_packge(Eigen3);   --> #find_packge(Eigen3); #delete this line;


so ,cmake will use the version of  "third_party/eigen" ; then I works;



## Describe:
 ###  1: I used   Anaconda to configure my environment,  and step by step followed [https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile](url),
but I met the error message above when I  did the command 'sudo make install';
### 2:I found that there was two versions of protobuf on my computer: one was installed by `conda install protobuf` and the other  by `brew install protobuf`;
When I do the command 'cd build && cmake .. ',the cmake  print  shows that the protobuf complier I used  was under the path of Anaconda; so I uninstalled the 2.6.0 version of protobuf,and installed the 3.2.0 version of protobuf used the command `conda install  protobuf=3.5.0`,and do the command `cd build && cmake .. && sudo make install `,the same  errors  occur; 
### 3: so I find out  the path of protobuf which I installed by the command `brew install protobuf`,and  `rm -rf /usr/local/bin/protoc@3.1 && rm -rf /usr/local/include/google/protobuf && rm -rf /usr/local/lib/libproto*`;then I  `cd build && cmake .. && sudo make install ` ,_errors also occur but the message is "This file was generated by a **newer** version of protoc which is...";_
### 4: Then  I `conda uninstall protobuf ` and `conda install protobuf=3.2.0`,and **_"rm -rf build"_**[Important!!!], `mkdir build && cd build && cmake ..  && sudo make install `,the question was solved!!!!

**Comment by pjh5** [comment]
Glad it's working now. Thanks for the detailed write-up!
