### ISSUE TITLE
Duplicating "Accurate, Large Minibatch SGD: Training ImageNet in 1 Hour"

### ISSUE THREAD

**Issue by wenwei202** [facebookarchive/caffe2#1780]
I am trying to duplicate the result in the paper of "[Accurate, Large Minibatch SGD: Training ImageNet in 1 Hour](https://arxiv.org/pdf/1706.02677.pdf)". Some basic questions before starting:
  1. Is [resnet50_trainer.py](https://github.com/caffe2/caffe2/blob/master/caffe2/python/examples/resnet50_trainer.py) the exact script to duplicate the result? What might not be included in the script?
  2. How to configure `redid_host`,`redis_port` and `file_store_path` for `resnet50_trainer.py`

**Comment by pietern** [comment]
Hi!

1. The LR schedule is not included. cc @prigoyal
2. You can choose to either use `file_store_path` for rendezvous IFF you have a filesystem that is shared between all participating machines. If you use this, every machine writes a number of files to this path that are then read by others. This is how they exchange TCP connection information. If you don't have a shared filesystem, you can use Redis for this rendezvous process. Instead of writing files, the machines will set a number of keys in a Redis instance that are then read by others. This only affects this initial rendezvous process. Once the communication channels are done setting up, they are not used further.

**Comment by pietern** [comment]
(closing the issue, but feel free to follow up)
