### ISSUE TITLE
error: ‘gflags’ has not been declared

### ISSUE THREAD

**Issue by SniperZhao** [facebookarchive/caffe2#1810]
If this is a build issue, please fill out the template below.

### System information

* Operating system: Centos7
* Compiler version: gcc 4.8.5
* CMake version: 2.8.11.2
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA): CUDA 8.0, cuDnn 6.0

### CMake summary output

```
******** Summary ********
-- Does not need to define long separately.
-- Current compiler supports avx2 extention. Will build perfkernels.
-- Found Protobuf: //lib64/libprotobuf.so;-pthread (found version "2.5.0") 
-- The BLAS backend of choice:Eigen
-- Could NOT find NNPACK (missing: NNPACK_INCLUDE_DIR NNPACK_LIBRARY PTHREADPOOL_LIBRARY CPUINFO_LIBRARY) 
-- Brace yourself, we are building NNPACK
-- Found PythonInterp: /bin/python (found version "2.7.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/six-download
[100%] Built target six
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/enum-download
[100%] Built target enum
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/opcodes-download
[100%] Built target opcodes
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/peachpy-download
[ 11%] Performing update step for 'peachpy'
Current branch master is up to date.
[ 22%] No configure step for 'peachpy'
[ 33%] No build step for 'peachpy'
[ 44%] No install step for 'peachpy'
[ 55%] No test step for 'peachpy'
[ 66%] Completed 'peachpy'
[100%] Built target peachpy
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/fp16-download
[ 11%] Performing update step for 'fp16'
Current branch master is up to date.
[ 22%] No configure step for 'fp16'
[ 33%] No build step for 'fp16'
[ 44%] No install step for 'fp16'
[ 55%] No test step for 'fp16'
[ 66%] Completed 'fp16'
[100%] Built target fp16
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/fxdiv-download
[ 11%] Performing update step for 'fxdiv'
Current branch master is up to date.
[ 22%] No configure step for 'fxdiv'
[ 33%] No build step for 'fxdiv'
[ 44%] No install step for 'fxdiv'
[ 55%] No test step for 'fxdiv'
[ 66%] Completed 'fxdiv'
[100%] Built target fxdiv
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/psimd-download
[ 11%] Performing update step for 'psimd'
Current branch master is up to date.
[ 22%] No configure step for 'psimd'
[ 33%] No build step for 'psimd'
[ 44%] No install step for 'psimd'
[ 55%] No test step for 'psimd'
[ 66%] Completed 'psimd'
[100%] Built target psimd
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/pthreadpool-download
[ 11%] Performing update step for 'pthreadpool'
Current branch master is up to date.
[ 22%] No configure step for 'pthreadpool'
[ 33%] No build step for 'pthreadpool'
[ 44%] No install step for 'pthreadpool'
[ 55%] No test step for 'pthreadpool'
[ 66%] Completed 'pthreadpool'
[100%] Built target pthreadpool
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/googletest-download
[100%] Built target googletest
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/fxdiv-download
[ 11%] Performing update step for 'fxdiv'
Current branch master is up to date.
[ 22%] No configure step for 'fxdiv'
[ 33%] No build step for 'fxdiv'
[ 44%] No install step for 'fxdiv'
[ 55%] No test step for 'fxdiv'
[ 66%] Completed 'fxdiv'
[100%] Built target fxdiv
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/googletest-download
[100%] Built target googletest
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/googlebenchmark-download
[100%] Built target googlebenchmark
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/googletest-download
[100%] Built target googletest
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/googlebenchmark-download
[100%] Built target googlebenchmark
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/googletest-download
[100%] Built target googletest
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build/googlebenchmark-download
[100%] Built target googlebenchmark
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.so)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.so)
-- Found lmdb    (include: /usr/include, library: /usr/lib64/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib64/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib64/libsnappy.so)
-- Could NOT find RocksDB (missing: RocksDB_INCLUDE_DIR RocksDB_LIBRARIES) 
-- OpenCV found (/lib64/cmake/OpenCV)
-- Did not find system Eigen. Using third party subdirectory.
-- Found PythonInterp: /bin/python (found suitable version "2.7.5", minimum required is "2.7") 
-- NumPy ver. 1.14.0 found (include: /usr/lib64/python2.7/site-packages/numpy/core/include)
-- Could NOT find pybind11 (missing: pybind11_INCLUDE_DIR) 
-- Could NOT find MPI_C (missing: MPI_C_COMPILER) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_COMPILER) 
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND) 
-- CUDA detected: 8.0
-- Added CUDA NVCC flags for: sm_20 sm_21 sm_30 sm_35 sm_50 sm_52 sm_60 sm_61
-- Found libcuda: /usr/local/cuda/lib64/libcuda.so
-- Found libnvrtc: /usr/local/cuda/lib64/libnvrtc.so
-- Found cuDNN: v6.0.21  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Could NOT find NCCL (missing: NCCL_INCLUDE_DIRS NCCL_LIBRARIES) 
-- NCCL: /usr/local/caffe2/third_party/nccl/build/lib/libnccl_static.a
-- Could NOT find CUB (missing: CUB_INCLUDE_DIR) 
-- Could NOT find Gloo (missing: Gloo_INCLUDE_DIR Gloo_LIBRARY) 
-- CUDA detected: 8.0
-- Found libcuda: /usr/local/cuda/lib64/libcuda.so
-- Found libnvrtc: /usr/local/cuda/lib64/libnvrtc.so
-- GCC 4.8.5: Adding gcc and gcc_s libs to link line
-- Include NCCL operators
-- Including image processing operators
-- Excluding video processing operators due to no opencv
-- Excluding mkl operators as we are not using mkl
-- MPI operators skipped due to no MPI support
-- Include Observer library
-- Automatically generating missing __init__.py files.
-- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.10.0-rc3
--   CMake command         : /usr/local/bin/cmake
--   Git version           : v0.8.1-991-g4358930
--   System                : Linux
--   C++ compiler          : /bin/c++
--   C++ compiler version  : 4.8.5
--   Protobuf compiler     : /bin/protoc
--   Protobuf include path : /usr/include
--   Protobuf libraries    : //lib64/libprotobuf.so;-pthread
--   CXX flags             :  -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.5
--     Python library      : //lib64/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 6.0.21
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.12
--     Snappy version      : 1.1.0
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.18
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : OFF
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.5
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/caffe2/build

```

After that I run the command:
make install
and the error message is:

/usr/local/caffe2/caffe2/core/flags.cc: In function ‘void caffe2::SetUsageMessage(const string&)’:
/usr/local/caffe2/caffe2/core/flags.cc:33:3: error: ‘gflags’ has not been declared
   gflags::SetUsageMessage(str);
   ^
/usr/local/caffe2/caffe2/core/flags.cc: In function ‘const char* caffe2::UsageMessage()’:
/usr/local/caffe2/caffe2/core/flags.cc:37:10: error: ‘gflags’ has not been declared
   return gflags::ProgramUsage();
          ^
/usr/local/caffe2/caffe2/core/flags.cc: In function ‘bool caffe2::ParseCaffeCommandLineFlags(int*, char***)’:
/usr/local/caffe2/caffe2/core/flags.cc:42:10: error: ‘gflags’ has not been declared
   return gflags::ParseCommandLineFlags(pargc, pargv, true);
          ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-invalid-partial-specialization" [enabled by default]
make[2]: *** [caffe2/CMakeFiles/caffe2.dir/core/flags.cc.o] Error 1
make[1]: *** [caffe2/CMakeFiles/caffe2.dir/all] Error 2
make: *** [all] Error 2

Can anyone give me any suggestion?

**Comment by pjh5** [comment]
@SniperZhao You seem to have a pretty old version of cmake. Can you try using a more recent cmake version with major version 3? 

You can also just turn gflags off with -DUSE_GFLAGS=OFF if you don't care about using it.

**Comment by SniperZhao** [comment]
@pjh5 Thank you very much for your suggestion.
Finally, I fixed it.
The instruction of Caffe2 on Centos Cloud on page: "https://caffe2.ai/docs/getting-started.html?platform=centos&configuration=cloud" is not correct for me at least.

People who has the same issue can follow the following command list:
1. install cmake version 3.10 by:
    1) wget "https://cmake.org/files/v3.10/cmake-3.10.0-rc3.tar.gz"
    2) tar -zxvf cmake-3.10.0-rc3.tar.gz
    3) cd cmake-3.10.0-rc3/
    4) ./bootstrap
    5) gmake 
    6) gmake install

2. install gflags by:
    1) git clone https://github.com/gflags/gflags.git
    2) cd gflags
    3) mkdir build
    4) cd build
    5) ${path_of_cmake_v3.10} -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_FLAGS='-fPIC' ..
    6) make -j8
    7) sudo make install
    8) cd ../..

3. install glog by:
    1) git clone https://github.com/google/glog.git
    2) cd glog
    3) ./autogen.sh && ./configure && make && make install

4. install Python Dependencies and CUDA as the formal caffe2 instruction did. (I did not do this because I have already installed CUDA 8.0 and cudnn 6.0 before)

5. install caffe2 by:
    1) git clone --recursive https://github.com/caffe2/caffe2
    2) cd caffe2 && mkdir build
    3) cd build && ${path_of_cmake_v3.10} ..
    4) sudo make -j8 install

6. if you can not import caffe2 and get error message such as: "ImportError: No module named caffe2.python". You can write such command: "export PYTHONPATH=${path_of_caffe2}/build:$PYTHONPATH" into your .bashrc file. And run command: "source .bashrc".

7. Enjoy your Caffe2 :)

**Comment by pjh5** [comment]
Thanks for the detailed comment @SniperZhao , I'm actively working on improving the installation process and instructions, so this is some great feedback. 

For anyone else reading this thread, I'd like to add a few things to the answer above.
- If you can, we strongly recommend installing Caffe2's dependencies (such as cmake, gflags, glog, protobuf) with a package manager rather than installing from source, both because it's faster, easier to debug, and less error prone. However this may not be an option for you if you are working on cloud machines, in which case installation from source like in the instructions above is required.
- The '-j8' in the `sudo make -j8 install` tells the build to use 8 processes. 8 is a good default but you can put anything here that you like. If you're getting out of memory errors then try decreasing this to 4 or 2.
- @SniperZhao it looks like you're setting your PYTHONPATH to the Caffe2 build directory. We don't actually recommend this because it might confuse python's import mechanism (https://stackoverflow.com/questions/14570011/explain-why-numpy-should-not-be-imported-from-source-directory). If Caffe2 installed correctly there should be a libcaffe2 somewhere on your machine (probably under /usr/local/) if you didn't manually override it. We recommend setting PYTHONPATH to point to this directory, where it can find libcaffe2

**Comment by emkooo** [comment]
I have also had big errors when trying to install Caffe2, after 2 days of digging and trying to find solutions to my errors I decided to re-install Ubuntu from **scratch** and installed Caffe2 by following several guides (including this one). I want to post my comments and way of triggering installations in order to pass through caffe2 installation on **ubuntu 16**.

Anyway, here is the complete installation I used from scratch and made it work (**FINALLY**).

**Credits:**
I want to thank SniperZhao, pjh5, and some references I used to be able to correct all errors that applied to me.

# Delete old drivers
sudo apt-get purge nvidia* 

# Add drivers PPA
sudo add-apt-repository ppa:graphics-drivers

# Update
sudo apt-get update 

#Install latest nvidia drivers. 390 as of march 2018
sudo apt-get install nvidia-390

# Restart 
sudo reboot

# setuptools
sudo apt-get install python-setuptools

# Install wheels
sudo pip install wheel


# Install dependencies
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      git \
      libgoogle-glog-dev \
      libgtest-dev \
      libiomp-dev \
      libleveldb-dev \
      liblmdb-dev \
      libopencv-dev \
      libopenmpi-dev \
      libsnappy-dev \
      libprotobuf-dev \
      openmpi-bin \
      openmpi-doc \
      protobuf-compiler \
      python-dev \
      python-pip                          
sudo -H pip install \
      future \
      numpy \
      protobuf

# for Ubuntu 16.04
sudo apt-get install -y --no-install-recommends libgflags-dev

# Get cuda 8.0
sudo apt-get update && sudo apt-get install wget -y --no-install-recommends
wget "http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb"
sudo dpkg -i cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
sudo apt-get update
sudo apt-get install cuda-8.0

# HERE YOU NEED TO MANUALLY DOWNLOAD CUDNN 6.1
# Extract and move to corr directioner

# Get and install cmake 3.10
wget "https://cmake.org/files/v3.10/cmake-3.10.0-rc3.tar.gz"
tar -zxvf cmake-3.10.0-rc3.tar.gz
cd cmake-3.10.0-rc3/
./bootstrap
make
make install


# /usr/local/bin/cmake
# Path to cmake v10.


# install gflags.
git clone https://github.com/gflags/gflags.git
cd gflags
mkdir build
cd build
/usr/local/bin/cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_FLAGS='-fPIC' ..
make -j8
sudo make install
cd ../..

# install autoconf
sudo apt-get install autoconf

#install libtool
sudo apt-get install libtool 

# INSTALL GLOG
git clone https://github.com/google/glog.git
cd glog
export LDFLAGS='-L/usr/local/lib' 
./autogen.sh && ./configure && make && sudo make install





#Libraries have been installed in:
#   /usr/local/lib
#
#If you ever happen to want to link against installed libraries
#in a given directory, LIBDIR, you must either use libtool, and
#specify the full pathname of the library, or use the '-LLIBDIR'
#flag during linking and do at least one of the following:
#   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
#     during execution
#   - add LIBDIR to the 'LD_RUN_PATH' environment variable
#     during linking
#   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
#   - have your system administrator add LIBDIR to '/etc/ld.so.conf'
#
#See any operating system documentation about shared libraries for
#more information, such as the ld(1) and ld.so(8) manual pages.





# CLONE CAFFE 2
git clone --recursive https://github.com/caffe2/caffe2
cd caffe2 && mkdir build
cd build && /usr/local/bin/cmake .. 
sudo make -j8 install

# If you get liobcaffe2_gpu.so or caffe2.python libcaffe2.so error
# Go to ~/.bashrc file and import pythonPath:
export PYTHONPATH=<yourpathtocaffe2>/build:$PYTHONPATH

# PS: I tried adding path to /usr/local/lib, /usr/local/
# Because linking to build is not recommended,
# However, I did not get it to work.

# Now do:
cd ~ && python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"

# Hope for SUCESS =)
