### ISSUE TITLE
make caffe2 error on ubuntu16.04

### ISSUE THREAD

**Issue by GeorgeBohw** [facebookarchive/caffe2#1851]
If this is a build issue, please fill out the template below.

### System information

* Operating system:ubuntu 16.04
* Compiler version:4.9.4
* CMake version:3.5.1
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):cuda-8.0   cudnn6.0

### CMake summary output

```
******** Summary ********
<please paste summary output here>
```
../lib/libcaffe2_gpu.so：对‘bool caffe2::ArgumentHelper::GetSingleArgument<bool>(std::string const&, bool const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::OpSchema::SetDoc(std::string const&)’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::gTypeNames()’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::StringToPadMode(std::string const&)’未定义的引用
../lib/libcaffe2_gpu.so：对‘double caffe2::ArgumentHelper::GetSingleArgument<double>(std::string const&, double const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&, void const*)’未定义的引用
../lib/libcaffe2_gpu.so：对‘bool caffe2::ArgumentHelper::HasSingleArgumentOfType<int>(std::string const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘bool caffe2::ArgumentHelper::HasSingleArgumentOfType<caffe2::NetDef>(std::string const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘unsigned short caffe2::ArgumentHelper::GetSingleArgument<unsigned short>(std::string const&, unsigned short const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘int caffe2::ArgumentHelper::GetSingleArgument<int>(std::string const&, int const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘google::base::CheckOpMessageBuilder::NewString()’未定义的引用
../lib/libcaffe2_gpu.so：对‘bool caffe2::ArgumentHelper::HasSingleArgumentOfType<float>(std::string const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::ArgumentHelper::HasArgument(std::string const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘google::protobuf::internal::StringTypeHandlerBase::New()’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::OpSchemaRegistry::map()’未定义的引用
../lib/libcaffe2_gpu.so：对‘caffe2::Workspace::GetBlob(std::string const&)’未定义的引用
../lib/libcaffe2_gpu.so：对‘short caffe2::ArgumentHelper::GetSingleArgument<short>(std::string const&, short const&) const’未定义的引用
../lib/libcaffe2_gpu.so：对‘std::unique_ptr<caffe2::RecurrentNetworkExecutorBase, std::default_delete<caffe2::RecurrentNetworkExecutorBase> > caffe2::createRNNExecutor<caffe2::CUDAContext>(caffe2::NetDef const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >&, std::string, caffe2::ArgumentHelper)’未定义的引用
../lib/libcaffe2_gpu.so：对‘std::vector<bool, std::allocator<bool> > caffe2::ArgumentHelper::GetRepeatedArgument<bool>(std::string const&, std::vector<bool, std::allocator<bool> > const&) const’未定义的引用

**Comment by GeorgeBohw** [comment]
anybody know how to solve it?i'll appreciate!

**Comment by GeorgeBohw** [comment]
i'm waiting for ur response

**Comment by amusi** [comment]
i also meet the same problem and can not solve it

**Comment by pjh5** [comment]
Is this using Anaconda? Can you run `find / -name libprotobuf* 2>/dev/null` and paste the output here? It looks a little like a protobuf error, so this https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile#null__protobuf-errors might be helpful to read through.

**Comment by GeorgeBohw** [comment]
there is conada in my computer，i cancel it and install protobuf again,then compile again，there is another issue：


Run Build Command:"/usr/bin/make" "cmTC_c446a/fast"
make[1]: Entering directory '/home/george/project/caffe2/build/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_c446a.dir/build.make CMakeFiles/cmTC_c446a.dir/build
make[2]: Entering directory '/home/george/project/caffe2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c446a.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_c446a.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_c446a
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c446a.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_c446a.dir/CheckFunctionExists.c.o  -o cmTC_c446a -rdynamic -lpthreads 
/usr/bin/ld: cann't find  -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_c446a.dir/build.make:97: recipe for target 'cmTC_c446a' failed
make[2]: *** [cmTC_c446a] Error 1
make[2]: Leaving directory '/home/george/project/caffe2/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_c446a/fast' failed
make[1]: *** [cmTC_c446a/fast] Error 2
make[1]: Leaving directory '/home/george/project/caffe2/build/CMakeFiles/CMakeTmp'

then i correct according to the otrhers' advise,like use "--recursive ",it didin't work!
how can i solve it?

**Comment by GeorgeBohw** [comment]
this is my env summary:

-- ******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1033-g0379390
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.1
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf include path : /usr/include
--   Protobuf libraries    : optimized;/usr/lib/x86_64-linux-gnu/libprotobuf.so;debug;/usr/lib/x86_64-linux-gnu/libprotobuf.so;-pthread
--   CXX flags             :  -Wno-deprecated -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.12
--     Python library      : /usr/lib/x86_64-linux-gnu/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 6.0.21
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.70
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 3.2.0
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF
-- Configuring incomplete, errors occurred!
See also "/home/george/project/caffe2/build/CMakeFiles/CMakeOutput.log".
See also "/home/george/project/caffe2/build/CMakeFiles/CMakeError.log".
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by GeorgeBohw** [comment]
now i have resolved the error about "lpthreads"!
it's strange,i have downloaded all the submodules,but not the right folder name（which change the lowercase to upercase）,correct that and it's ok now!

**Comment by pjh5** [comment]
Glad that it's working now. Please open another issue if you come across any more problems.

**Comment by GeorgeBohw** [comment]
ok,thanks！

**Comment by bzwqq** [comment]
now i meet the same error about 'lpthreads'.    how did you solve this problem?  which folder name should change to upercase?

**Comment by pjh5** [comment]
@bzwqq what operating system are you on and how did you install Caffe2?

**Comment by bzwqq** [comment]
-- ******** Summary ********
-- General:
--   CMake version         : 3.8.1
--   CMake command         : /usr/local/bin/cmake
--   Git version           : unknown
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 4.8.4
--   Protobuf compiler     : /usr/local/bin/protoc
--   Protobuf include path : /usr/local/include
--   Protobuf libraries    : /usr/local/lib/libprotobuf.so;-lpthread
--   BLAS                  : Eigen
--   CXX flags             :  -Wno-deprecated -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.13
--     Python library      : /home/bimingwei/anaconda2/lib/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 7.0.3
--     CUDA root directory : /usr/local/cuda-8.0
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     CUDA NVRTC library  : /usr/local/cuda-8.0/lib64/libnvrtc.so
--     CUDA runtime library: /usr/local/cuda-8.0/lib64/libcudart.so
--     CUDA include path   : /usr/local/cuda-8.0/include
--     NVCC executable     : /usr/local/cuda-8.0/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.15
--     Snappy version      : 1.1.0
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.10
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 3.1.0
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF
-- Configuring incomplete, errors occurred!
See also "/home/bimingwei/caffe2Workspace/caffe2-master/build/CMakeFiles/CMakeOutput.log".


 because git clone is too slow, i download the caffe2.zip from github website directly, and do  make .

**Comment by bzwqq** [comment]
@pjh5  my env is as follows. because git clone is too slow, i download the caffe2-master.zip from github website directly, and do make.  then the error happens.
 -- ******** Summary ********
-- General:
--   CMake version         : 3.8.1
--   CMake command         : /usr/local/bin/cmake
--   Git version           : unknown
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 4.8.4
--   Protobuf compiler     : /usr/local/bin/protoc
--   Protobuf include path : /usr/local/include
--   Protobuf libraries    : /usr/local/lib/libprotobuf.so;-lpthread
--   BLAS                  : Eigen
--   CXX flags             :  -Wno-deprecated -std=c++11 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.13
--     Python library      : /home/b/anaconda2/lib/libpython2.7.so
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 7.0.3
--     CUDA root directory : /usr/local/cuda-8.0
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     CUDA NVRTC library  : /usr/local/cuda-8.0/lib64/libnvrtc.so
--     CUDA runtime library: /usr/local/cuda-8.0/lib64/libcudart.so
--     CUDA include path   : /usr/local/cuda-8.0/include
--     NVCC executable     : /usr/local/cuda-8.0/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.15
--     Snappy version      : 1.1.0
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.10
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 3.1.0
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_THREADS           : ON
--   USE_ZMQ               : OFF
-- Configuring incomplete, errors occurred!
See also "/home/b/caffe2Workspace/caffe2-master/build/CMakeFiles/CMakeOutput.log".

**Comment by pjh5** [comment]
@bzwqq do you still get this problem? What exactly is the error you are getting? What's your protobuf version?

**Comment by bzwqq** [comment]
no,i have solved the problem when i git clone completely rather than download the zip. thank you very much
