### ISSUE TITLE
caffe2

### ISSUE THREAD

**Issue by tchenai** [facebookarchive/caffe2#1923]
If this is a build issue, please fill out the template below.

### System information

* Operating system:
* Compiler version:
* CMake version:
* CMake arguments:
* Relevant libraries/versions (e.g. CUDA):

### CMake summary output

```
******** Summary ********
<please paste summary output here>
```

**Comment by pjh5** [comment]
Hi @tchenai do you have a problem or question regarding Caffe2? If you do, please create an issue with the error or question as the issue name, and please post the information in the form you gave. For example, for me it'd be

System information

    Operating system: macOS 13.1
    Compiler version: gcc 5.1
    CMake version: 3.5.1
    CMake arguments: -DUSE_CUDA=OFF
    Relevant libraries/versions (e.g. CUDA): None

In the meantime I will close this issue due to lack of information.
