### ISSUE TITLE
test failed with No module named 'onnx.onnx_pb' 

### ISSUE THREAD

**Issue by liqunfu** [facebookarchive/caffe2#2133]
On a windows 10 anaconda python 3.6 environment, I followed the installation instruction:
git clone --recursive https://github.com/onnx/onnx.git
conda install -c conda-forge protobuf numpy
(in cntk)
pip install onnx 
(in cntk/cntk in order to avoid ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export')
python -c "import onnx"
pip install pytest-cov nbval
(no error from above steps.)

pytest
(I am getting following type of errors when running pytest)
============================= test session starts =============================
platform win32 -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: D:\onnx, inifile: setup.cfg
plugins: nbval-0.9.0, cov-2.5.1
collected 9 items / 10 errors

----------- coverage: platform win32, python 3.6.1-final-0 -----------
Name          Stmts   Miss  Cover   Missing
-------------------------------------------
__init__.py      22     17    23%   7-49

=================================== ERRORS ====================================
__________________ ERROR collecting onnx/backend/test_rnn.py __________________
ImportError while importing test module 'D:\onnx\onnx\backend\test_rnn.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
__init__.py:6: in <module>
    from .onnx_pb import *  # noqa
E   ModuleNotFoundError: No module named 'onnx.onnx_pb'
__________________ ERROR collecting onnx/test/basic_test.py ___________________

**Comment by pjh5** [comment]
This test actually requires onnx to be installed alongside Caffe2. Can you try `pip install onnx` or `pip install <caffe2_root>/third_party/onnx` . If an onnx installation is in the same site-packages as your Caffe2 installation then this should work.

Or, if you only care about Caffe2 right now, then you can just delete all the tests that try to import onnx.

**Comment by liqunfu** [comment]
@pjh5 I do not have caffe2 installed. I installed onnx as described in my post and got this error (missing onnx.onnx_pb) message. 
@yinghai I do not have caffe2. I ran your suggestion anyway but still get the same error. 

Is it possible that the instruction of installing ONNX from source is outdated? It does not look like building anything from source.

**Comment by pjh5** [comment]
Oh I see. I think you should post this issue here https://github.com/onnx/onnx/issues instead then, as it seems unrelated to Caffe2. 

I am not that sure about how Windows works, but I would guess that this path "D:\onnx\onnx\backend\test_rnn.py" in your error message should actually by "<path to anaconda root directory>/Lib/site-packages/onnx/onnx/backend/test_rnn.py" or something like that. Perhaps there's an environment variable that determines where python searches for packages?

Are you sure that 1) your anaconda environment is working correctly and you can import other conda and pip packages okay and 2) that the pip you used is installing into the conda environment you want?

**Comment by pjh5** [comment]
I am closing as this is not a Caffe2 issue, but still feel free to ask questions here if you think I can help.
