### ISSUE TITLE
Can I use Caffe2 with python2 though I compiled caffe2 with python3

### ISSUE THREAD

**Issue by hangwudy** [facebookarchive/caffe2#2557]
Hello everyone,
I compiled caffe2 with the command `FULL_CAFFE2=1 python setup.py install`. However, the default python version is 3.6. 
After installation, I can use caffe2 with python3. 
But by python2, I met the problem:
`Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.

`from caffe2.python import core`
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
CRITICAL:root:Cannot load caffe2.python. Error: No module named caffe2_pybind11_state
`

How can I solve the problem?

**Comment by orionr** [comment]
Hi @hangwudy - when you did an install it copied content into your default site packages. If you're using python 2.7 likely you'll want to use virtualenv or conda so the `FULL_CAFFE2=1 python setup.py install` will install into that specific site package. Please also make sure you are using latest master on `pytorch/pytorch` to run this, since we had some issue with files not copying correctly a few days ago. Also you can eliminate FULL_CAFFE2=1 now and just run

```
python setup.py install
```
and that should give you `torch` and `caffe2`.

 Please open an issue on https://github.com/pytorch/pytorch/issues/ if you still have issues.
