### ISSUE TITLE
Any future support for Python3 ?

### ISSUE THREAD

**Issue by xnming** [facebookarchive/caffe2#284]
Is there any official plan to support Python3 in the future ? Python 2.7 is still the default choice for caffe2, this means that windows users will make lots of extra efforts to write C/C++ extensions. Python2.7 requires an old C++ compiler(vc9) to work, and it does not support the newest CUDA toolkit. I think the Python2.7 support for windows platform should be aborted for caffe2 to leverage the newest Visual C++ Compiler (vc14 or higher). And this is the what has been done in tensorflow.

**Comment by Yangqing** [comment]
Yep, we are ironing out several issues regarding string manipulation, so expect it to be done soon. Regarding python 2.7 support - we actually tried doing Visual C++ 14 with cuda in release mode, so if you'd like to give that a try it would be really nice. The script can be found at scripts/build_windows.bat.

**Comment by xnming** [comment]
@Yangqing Thanks for your reply. I will have a try at this moment and create a PR when it is ready.

**Comment by Yangqing** [comment]
@xnming That is super, thanks!

The current windows settings that we are monitoring can be found here: https://github.com/caffe2/caffe2/blob/master/appveyor.yml

**Comment by wensheng** [comment]
Python 2.7 with VS2015 and cuda 8.0 works.

I have to make these changes.

In cmake/Cuda.cmake:

    remove "20 21(20) " from 3rd line

In scripts/build_windows.bat:

    add "SET USE_CUDA=ON" at the beginning of the file
    add "-DCUDA_ARCH_NAME=Manual ^" to the cmake lines

Because I use VS2015, I added:

    SET CMAKE_GENERATOR="Visual Studio 14 2015 Win64"

to both build_windows.bat and build_host_protoc.bat

I run build_windows.bat under "Developer Command Prompt for VS2015" cmd.exe.  There're loads of warnings but no error.

But yeah, python3 support would be so much better, I avoid using python2 whenever I can.

**Comment by Yangqing** [comment]
#315 set up to track python3 support.
