### ISSUE TITLE
Android Build (linking issue)

### ISSUE THREAD

**Issue by kindloaf** [facebookarchive/caffe2#297]
Hi,
I have a question regarding the Android build. I used "make android" to cross compile.
The compilation worked fine. For linking, the linker tried to use some dynamic libraries from system folder, such as /usr/local/lib/libopencv_core.so, which was build for x86.
Any advice on how to make linker look for the right libraries?

**Comment by Yangqing** [comment]
Ah, this might be because the Android cmake script is finding incorrect libraries. You may want to explicitly turn off these dependencies. For example, for opencv, you should pass in -DUSE_OPENCV=OFF. For a list of the options see here:

https://github.com/caffe2/caffe2/blob/master/CMakeLists.txt#L40-L61

**Comment by Yangqing** [comment]
(closing but feel free to reopen)

**Comment by kindloaf** [comment]
@Yangqing Thanks for the help. By turning off the switch it works now.
