### ISSUE TITLE
Installed anaconda2 how to configure Protobuf

### ISSUE THREAD

**Issue by zgq91** [facebookarchive/caffe2#302]
Hi:
     When I execute the cmake .. command the following error occurs:
      Could NOT find Protobuf (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
CMake Error at cmake/ProtoBuf.cmake:21 (message):To build protobufs locally (required for Android/iOS/Windows), you will  need to manually specify a PROTOBUF_PROTOC_EXECUTABLE. 
    My system has already installed anaconda2.
　 Looking forward to your reply.

**Comment by Yangqing** [comment]
You might want to install the C++ protobuf part as well - which platform do you use? Installation instructions here might be helpful:

http://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile

(Closing the issue for now but feel free to follow up)

**Comment by zgq91** [comment]
my  platform is  unbuntu 16.04

**Comment by aaronmarkham** [comment]
If you follow this guide you should be able to build on Ubuntu 16.04: http://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile

Note that you are installing protobuf at the system level and then you install protobuf for python. 

```
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      git \
      libgoogle-glog-dev \
      libprotobuf-dev \
      protobuf-compiler \
      python-dev \
      python-pip                          
sudo pip install numpy protobuf
```

You could try to use Anaconda instead of pip to install protobuf, but this has yet to be fully tested on Ubuntu 16.04. You may run into some versions problems and have to force install something other than the default package.
Like this:

```
conda install -y --channel https://conda.anaconda.org/conda-forge  \
gflags \
glog  \
numpy \
protobuf=3.2.0
```
