### ISSUE TITLE
if there any simple guide for runing test process?

### ISSUE THREAD

**Issue by machoji** [facebookarchive/caffe2#35]
thanks to great caffe, I learnt a lot.
If Caffe2 has some simple guide for running a test process? I have installed and compiled it  successfully, but cannot run it. 
Even I cannot find the main function, can you give some help? or can i invite you to help me in zhihu?

**Comment by xsz** [comment]
Unlike caffe, Caffe2 does not have a main function. Instead, it is a C++ library and called by upper-level Python wrapper(its interface is in caffe2_python.cc). 
The core.py file is responsible for translating you network definition into protobuf string and core/net.cc file for actually creating the network through instantiating a series of operators.
In Caffe2, all operations are defined in operators, the forward-propagation and backward-propagation are seperated into two operators. The input/intermediate blobs and parameter blobs are treated equally. Besides, blobs now are just an abstract, the real data is stored in tensors to distinguish different contexts(CPU, CUDA, CUDNN).
Caffe2 can potentially be parallelized with MPI because some communication operators(broadcast and allreduce) have been defined in mpi directory. You can use these operators to construct the network.
Caffe2 also has the potential ability to auto-generate CUDA codes through cuda-rtc which is the key to support user-defined operations on GPUs.

The example is in notebooks directory and you can read the *.ipynb files.

As an active student learner of Caffe2, here I share some of my understandings. I hope this can help you.

## 

Xu Shizhen
Room 3-126, FIT Building
Institute of High Performance Computing
Department of Computer Science and Technology
Tsinghua University
Beijing, China, 100084

At 2016-06-06 16:39:16,machoji notifications@github.com wrote:

thanks to great caffe, I learnt a lot.
If Caffe2 has some simple guide for running a test process? I have installed and compiled it successfully, but cannot run it.
Even I cannot find the main function, can you give some help?
