### ISSUE TITLE
Cannot compile on Windows 10

### ISSUE THREAD

**Issue by salos1982** [facebookarchive/caffe2#357]
I have some issues with compilation. I'm following https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile

first of all 
conda install -y --channel https://conda.anaconda.org/eugene protobuf
does not work. there is following error
C:\WINDOWS\system32>conda install -y --channel https://conda.anaconda.org/eugene protobuf
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - protobuf -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

Then after cloning git repository (using gitgub extension or git) I have no batch file to run. I found some similar files in scripts folder but they are required APPVEYOR_BUILD_WORKER_IMAGE environment variable. What is it I do not understand and how to compile too.

**Comment by aaronmarkham** [comment]
I will look into this today (will see if we can get past the protobuf version issues), but the first thing to note is that until we have Python 3x support you should install [Anaconda Python 2.7](https://repo.continuum.io/archive/Anaconda2-4.3.1-Windows-x86_64.exe), or try using a 2.7 conda environment. Another approach that may do the trick and avoid problems with which Python is getting used, go for vanilla Python 2.7, and build protobuf from source. The anaconda-forge channel doesn't seem to have a package for win64 for protobuf yet, so that's why these other community supplied packages were listed.

**Comment by salos1982** [comment]
I could pass this step at home using clean installation of Visual Studio 20017 (at work I Have Visual Studio 2015). I got sln file. However it does not build. There are errors in project caffe2_pybind11_state

11>D:\Projects\caffe2\caffe2\python\pybind_state.cc(202): error C3861: PyString_AsString: идентификатор не найден (identifier not found)
11>D:\Projects\caffe2\caffe2\python\pybind_state.cc(204): error C3861: PyString_AsString: идентификатор не найден (identifier not found)
11>D:\Projects\caffe2\caffe2\python\pybind_state.cc(322): error C3861: PyString_Check: идентификатор не найден (identifier not found)
11>D:\Projects\caffe2\caffe2\python\pybind_state.cc(824): error C3861: PyString_Check: идентификатор не найден (identifier not found)
11>D:\Projects\caffe2\caffe2\python\pybind_state.cc(907): warning C4003: не хватает фактических параметров для макроопределения "import_array1" (not enough parameters for macro import_array1)

**Comment by crohkohl** [comment]
A simple solution for me was to replace `PyString_AsString` by `PyUnicode_AsUTF8` and `PyString_Check` by `PyUnicode_Check`.

**Comment by Yangqing** [comment]
This is related to python3 support - please check #315.
