### ISSUE TITLE
caffe2 + python layer?

### ISSUE THREAD

**Issue by RSly** [facebookarchive/caffe2#366]
Hi,

I couldn't find out if/how caffe2 supports python layers for the data and loss functions.
is there any example on this?

since https://github.com/BVLC/caffe/issues/2936 , caffe supports multi-gpu python layers which is very nice
any tip is helpful :)

**Comment by Yangqing** [comment]
Yeah, we do support python operators - see this for a few examples:

https://github.com/caffe2/caffe2/blob/master/caffe2/python/python_op_test.py

However, as you suspected, the python operators are inherently serialized right now due to GIL. The other C++ operators will run in parallel if you use net types such as DAG, though.

**Comment by RSly** [comment]
thanks @yangqing for the answer.
as you know the gil restrictions are not easy to solve. however a good strategy to parallelize was implemented in https://github.com/BVLC/caffe/pull/4563

 a traincaffe2.py can be of great intrest !
