### ISSUE TITLE
Error while building android version on Mac

### ISSUE THREAD

**Issue by jimmylilyy** [facebookarchive/caffe2#538]
I could build iOS version successfully, but error occurs while building android version:

/caffe2/caffe2/core/blob_serialization.h:251:28: error: there are no arguments to 'processChunk' that depend on a template parameter, so a declaration of 'processChunk' must be available [-fpermissive]
     processChunk(chunkBegin);

Checking the code that it seems **processChunk** is defined under **#ifndef __ANDROID__** macro,  but used beyond this scope;

**Comment by ThomasGueldner** [comment]
I am having the same problem, but I am building under Ubuntu 16.04. Couldn't solve this problem yet :(.

**Comment by ThomasGueldner** [comment]
There is a PR #543 out there which seems to be able to cope with your and my issue. I just modified the file ```blob_serialization.h``` the same way as suggested in the PR and then I was able to successfully build for android (**using Ubuntu**). Unfortunately, I cannot confirm whether it would also work on **MAC**, because I don't have a MAC here.

**Comment by jimmylilyy** [comment]
Tks! The PR #543 fixed my issue too. So close the issue!
