### ISSUE TITLE
How to build caffe2 in Windows with MKL for fast inference?

### ISSUE THREAD

**Issue by bachml** [facebookarchive/caffe2#544]
I've been trying few days working on build dnn frameworks with MKL as BLAS backend. 
I think caffe2 + mkl would be a very promising solution, but it's hard to link MKL in windows. 
Has anybody work on it?
Thanks~

**Comment by matzeox** [comment]
Building caffe2 with MKL in windows works for me.
But you'll get runtime errors, because caffe2 needs some functions which are not implemented anymore in the current version of MKL 2017.

See the following issue: https://github.com/caffe2/caffe2/issues/514

I hope that this will be fixed soon by the caffe2 people.
