### ISSUE TITLE
Using ibverbs for Infiniband in Caffe2 with Gloo

### ISSUE THREAD

**Issue by ambujpd** [facebookarchive/caffe2#616]
Hi,

With Resnet50 on multi-node, I've not been able to use ibverbs transport in Caffe2 for communication using Infiniband.

I've compiled gloo with `set(USE_IBVERBS_DEFAULT ON)` in Caffe2.

While doing cmake, it shows `-- Found ibverbs (include: /usr/include, library: /usr/lib/libibverbs.so)`.

Is there any hook we can choose while running Resnet50 to choose between TCP or ibverbs transport?

Also, will IPoIB work with TCP transport (it should ideally, but performance won't be similar to ibverbs implementation I suppose).

@pietern

**Comment by pietern** [comment]
Hi @talk2ap001, this is unfortunately still hard coded to use TCP here: https://github.com/caffe2/caffe2/blob/master/caffe2/contrib/gloo/common_world_ops_gpu.cc. The operator needs to be modified to take some extra args to pick up an ibverbs device if configured to do so. We have been using Caffe2 only with the TCP transport so far, which is why this is missing. Updating it to include those options is not hard through, so I'll track it through this task.

**Comment by ambujpd** [comment]
Thanks @pietern for the info. This would be a really important enhancement for distributed learning.

I unfortunately only have 1 Gbps Ethernet connection link between my servers which is why I'm only witnessing a 1.3X speedup when scaling from 1 node (2 GPUs) to 2 nodes (4 GPUs). But I also have a 50 Gbps Infiniband and it would really be important to utilize it for this purpose.

**Comment by ambujpd** [comment]
This will also give boost via GPUDirect RDMA.

**Comment by pietern** [comment]
I've found GPUDirect to not be beneficial in all cases though, since it also means you have to launch a kernel for reducing intermediary results, which amplifies the overhead for very small buffers to reduce. The launch overhead only causes contention on the GPU and slows down the backwards pass. I've seen much better performance by reducing the small stuff on the CPU / system memory. Another solution is of course to concat your small gradients and run a single reduction.

Though I think we chatted about this in person as well :)

**Comment by renganxu** [comment]
@ambujpd @pietern  Do you mean the current Caffe2 implementation could not use ibverbs library? 

I got ~700 images/sec within 1 node with has 4 GPUs, but with 2 nodes, the speed is only 250 images/sec per node. I noticed all the data went through Ethernet interface although my nodes are connected with 100Gbps Infiniband. I tried to compile Caffe2 with -DUSE_IBVERBS_DEFAULT=ON, but still no success. The communication still goes through Ethernet interface.

**Comment by zhjliucsc** [comment]
@pietern Not sure if this issue has been taken care of. here are some outputs from my cases.
 
I modified common_world_ops_gpu.cc to hard-code the ib device info. to enable ibverbs transport for caffe2.
==================================================
#ifdef ANDY_USE_TCP
    ::gloo::transport::tcp::attr attr;
    device = ::gloo::transport::tcp::CreateDevice(attr);
#endif
#ifdef ANDY_USE_IBVERBS
    ::gloo::transport::ibverbs::attr attr = {
      .name = "mlx4_0",
      .port = 2,
      .index = 1,
    };
    device = ::gloo::transport::ibverbs::CreateDevice(attr);
#endif
===============================================

When I ran resnet_50 between two machines, I got the following error on one machine:
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /home/andy/Downloads/caffe2/third_party/gloo/gloo/transport/ibverbs/pair.cc:466] wc->status == IBV_WC_SUCCESS. 8 vs 0. Memory region send for slot 0: local access error

and another machine:
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /home/andy/Downloads/caffe2/third_party/gloo/gloo/transport/ibverbs/pair.cc:466] wc->status == IBV_WC_SUCCESS. 8 vs 0. Memory region send for slot 0: local access error 

The TCP transport always works well though.  

BUT when I did the same on gloo benchmark, by hard-coding the options.h where the default device attr is defined, the gloo benchmark using ibverbs actually went successfully between the two machines. This means to me that the issue is caffe2 doesn't invoke gloo+ibverbs correctly.

Would you please shed some lights on this?

Thanks,
Andy

**Comment by zhjliucsc** [comment]
@pietern Would it be possible for you to share some code snippet to show us how to use gloo/ibverbs in caffe2? I understand that to add configurable options between tcp/ibverbs and the attr can take some labor, but hard-coded way would be good enough for our needs, we just like to understand the minimum requirements/steps :) 

Thanks,
Andy

**Comment by renganxu** [comment]
@zhjliucsc I have similar error even with gloo benchmark:
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /cm/shared/scratch/Caffe2/gloo/gloo/transport/ibverbs/pair.cc:466] wc->status == IBV_WC_SUCCESS. 12 vs 0. Memory region send for slot 0: **transport retry counter exceeded**

Did you have this "transport retry counter exceeded" error before?

I think you can let caffe2 link to the gloo library compiled by yourself, not the library compiled by caffe2. Let us know if you have any success.

Thanks,
Rengan

**Comment by zhjliucsc** [comment]
@hfutxrg I can run gloo benchmark with ibverbs transport correctly, but no luck when trying caffe2 over ibverbs. thanks.

**Comment by bkovalev** [comment]
@zhjliucsc Can you provide me how you install CAFFE2 with ibverbs enabled?

**Comment by bkovalev** [comment]
./benchmark_cuda --size 2 --rank 0 --redis-host 12.12.12.28 --redis-port 6379 --prefix 1301 --transport ibverbs --elements -1 cuda_allreduce_ring_chunked
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /root/gloo/gloo/benchmark/runner.cc:55] device_. Unknown transport: ibverbs
Aborted (core dumped)

**Comment by renganxu** [comment]
Hi @pietern and @zhjliucsc, any update on this issue? Based on @zhjliucsc code snippet to use ibverbs library in Caffe2, I got the following errors:

on one node:
``mlx5: node006.ib.cluster: got completion with error:``
``00000000 00000000 00000000 00000000``
``00000000 00000000 00000000 00000000``
``00000004 00000000 00000000 00000000``
``00000000 9200c211 00000086 0003d9e0``
``terminate called after throwing an instance of 'gloo::EnforceNotMet'``
  ``what():  [enforce fail at /cm/shared/scratch/rengan/caffe2-ibverbs/third_party/gloo/gloo/transport/ibverbs/pair.cc:470] wc->status == IBV_    WC_SUCCESS. 8 vs 0. Memory region send for slot 0: local access error``

on another node:
 ``mlx5: node016.ib.cluster: got completion with error:``
``00000000 00000000 00000000 00000000``
 ``00000000 00000000 00000000 00000000``
 ``00000004 00000000 00000000 00000000``
 ``00000000 00008813 09000096 00032ad0``
 ``terminate called after throwing an instance of 'gloo::EnforceNotMet'``
   ``what():  [enforce fail at /cm/shared/scratch/rengan/caffe2-ibverbs/third_party/gloo/gloo/transport/ibverbs/pair.cc:423] wc->status == IBV_    WC_SUCCESS. 10 vs 0. Send for slot 1: remote access error``

This version I ran on RHEL is an old version "commit 2e2d00f161f874ccbdea1ac209352e31a86e133eI" because the latest version has the type cast error which I mentioned in the issue https://github.com/caffe2/caffe2/issues/999.  In this version, I have already used the latest Gloo library. Do you know how to solve this issue?

**Comment by renganxu** [comment]
I also tried the latest Caffe2 from github (commit f0ea8046c26d9c324dc34deb2bfd8e3738e9f02c) and tried to use ibverb on two Ubuntu nodes. Both nodes have the following error:

INFO:data_parallel_model:Parallelizing model for devices: [0, 1, 2, 3]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Model for GPU : 2
INFO:data_parallel_model:Model for GPU : 3
INFO:data_parallel_model:Parameter update function not defined --> only forward
Traceback for operator 3 in network resnet50_test
/mnt/Caffe2/caffe2/build/caffe2/python/helpers/conv.py:121
/mnt/Caffe2/caffe2/build/caffe2/python/helpers/conv.py:167
/mnt/Caffe2/caffe2/build/caffe2/python/brew.py:99
/mnt/Caffe2/caffe2/build/caffe2/python/models/resnet.py:234
/mnt/Caffe2/caffe2/build/caffe2/python/examples/resnet50_trainer.py:267
/mnt/Caffe2/caffe2/build/caffe2/python/data_parallel_model.py:167
/mnt/Caffe2/caffe2/build/caffe2/python/examples/resnet50_trainer.py:349
/mnt/Caffe2/caffe2/build/caffe2/python/examples/resnet50_trainer.py:462
/mnt/Caffe2/caffe2/build/caffe2/python/examples/resnet50_trainer.py:466
/usr/lib/python2.7/runpy.py:72
/usr/lib/python2.7/runpy.py:174
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/Caffe2/caffe2/build/caffe2/python/examples/resnet50_trainer.py", line 466, in <module>
    main()
  File "/mnt/Caffe2/caffe2/build/caffe2/python/examples/resnet50_trainer.py", line 462, in main
    Train(args)
  File "/mnt/Caffe2/caffe2/build/caffe2/python/examples/resnet50_trainer.py", line 352, in Train
    workspace.CreateNet(test_model.net)
  File "/mnt/Caffe2/caffe2/build/caffe2/python/workspace.py", line 147, in CreateNet
    StringifyProto(net), overwrite,
  File "/mnt/Caffe2/caffe2/build/caffe2/python/workspace.py", line 166, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at operator.cc:30] blob != nullptr. op Conv: Encountered a non-existing input blob: gpu_0/conv1_w

Hope this issue can be solved soon. @pietern

**Comment by skyde1021** [comment]
@hfutxrg I have the same error. This error is related to GPUDirect.
If you turn on GPUDirect while using infiniband, you will get the same error using GLOO only.
However, if GPUDirect is turned off in the GLOO, the error disappears.
CAFFE2 has used these GPUDirect as defaults.

And ... did anyone solve this problem?

**Comment by pietern** [comment]
@hfutxrg The "local access error" problem is usually caused by trying to reuse a stale rendezvous. A node then finds peering information in the backing store (file system or Redis) and tries to use it immediately. Because the information belonged to a previous run, the queue pair information and address mapping is invalid, causing the access  errors.

The second problem you list is something different -- your process can't find a blob. This is not specific enough to attach a particular cause. I'm positive using a newer version of C2 would have solved that.

@skyde1021 / @hfutxrg Last month I added #1203 which checks the Gloo transport for GPUDirect support, and if present, makes the Gloo algorithms use GPUDirect when the input blobs are located in GPU memory. Related to this, you still have to make CreateCommonWorld use the ibverbs transport and the right IB device of course, which is addressed in #1177. In particular, see [this change to resnet50_trainer.py][1] for an example how this is used. You can specify `transport="ibverbs"` and `interface="mlx5_0"` for example to use the first IB device in your system.

[1]: https://github.com/caffe2/caffe2/commit/e5526cc991c686163e0a19446b29ef1c408c0190#diff-a8d23b923c9f225d91efe7a4f068f986

**Comment by pietern** [comment]
I'm closing this issue since the original problem has been addressed. If you have trouble using this code, please feel free to open a new issue.
