### ISSUE TITLE
Setting engine in brew.conv doesn't override use_cudnn

### ISSUE THREAD

**Issue by lukeyeager** [facebookarchive/caffe2#860]
This non-intuitive behavior is giving @slayton58 trouble while working on https://github.com/caffe2/caffe2/pull/833.
```python
>>> from caffe2.python import brew, model_helper
>>> model = model_helper.ModelHelper()
>>> brew.conv(model, 'conv_in', 'conv_out', 10, 10, 5, engine='')
BlobReference("conv_out")
>>> print('Proto: "%s"' % model.Proto())
Proto: "name: "model"
op {
  input: "conv_in"
  input: "conv_out_w"
  input: "conv_out_b"
  output: "conv_out"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 5
  }
  arg {
    name: "exhaustive_search"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  engine: "CUDNN"
  uuid: 14532784363511038896
}
external_input: "conv_in"
external_input: "conv_out_w"
external_input: "conv_out_b"
"
```

**Comment by slayton58** [comment]
\cc @Yangqing 

This is tricky, because defaulting to `use_cudnn=True` in `ModelHelper` is useful for normal runs, but a mess during testing (which as Luke mentioned is tripping me up).

Another way of working around this would be to explicitly setup ModelHelper without cuDNN for all testing runs (presumably abstracting out the creation of ModelHelper so that it can be modified centrally
