### ISSUE TITLE
no brew in docker image?

### ISSUE THREAD

**Issue by thnkim** [facebookarchive/caffe2#900]
Hello,
I got 'ImportError: cannot import name brew' when I try to use brew as in Tutorial (MNIST - Create a CNN from Scratch).
It looks the latest of docker images is outdated (last pushed: 2 months ago). Can I get an updated docker? 

If I try to 'git pull' and build in docker container, I got a build error:
'/caffe2/caffe2/contrib/gloo/context.cc:5:24: fatal error: gloo/types.h: No such file or directory'.

Thank you.

**Comment by aaronmarkham** [comment]
As a quick solution you can try this Dockerfile - it will get the latest source:
https://github.com/caffe2/caffe2/blob/gh-pages/docker/ubuntu-16.04-gpu-tutorial/Dockerfile
But I'd add to the python installation some dependencies that have been added since the creation of that file: six, future

Also look at #911 since that may work for you.
