### ISSUE TITLE
[enforce fail at tensor_protos_db_input.h:68] protos.protos_size() == OutputSize().

### ISSUE THREAD

**Issue by attitudechunfeng** [facebookarchive/caffe2#935]
I have come across a problem which indicates "[enforce fail at tensor_protos_db_input.h:68] protos.protos_size() == OutputSize()." when i try to run lenet with my own lmdb data. Can anybody tell me how to deal with this problem. Many thanks.

**Comment by leovandriel** [comment]
This is caused by your database having an incorrect number of protos per row in the database. To quote the docs of the `TensorProtosDBInput` operator:

> The number of output tensors is equal to the size of (number of TensorProto’s in) the TensorProtos objects stored in the DB as values.

Typically every row contains two tensors: one with the label and one the data for that label. However, that is completely dependent on your setup. If you could share how you populate the database and how you configured the operator, we can figure out where the problem lies exactly.

**Comment by attitudechunfeng** [comment]
Thank u very much！@leonardvandriel I have figured out this problem. And as you what you said, the error is caused by the preparation of data. I modified the codes, and then it worked.

**Comment by blateyang** [comment]
I met almost the same problem,"Prefetching error [enforce fail at tensor_protos_db_input.h:84] protos.protos_size() == OutputSize()" , when I try to run a net with cifar-10 lmdb data created by create_cifar10.sh in caffe/example/cifar10. I have tested that the data can be loaded and trained normally in caffe. Can you tell me how to deal with this problem. Thanks a lot. @leonardvandriel

**Comment by CarlosYeverino** [comment]
Hello @attitudechunfeng @blateyang ,

I am in a similar situation as you described. Did you manage to solve this issue? If yes, how did you solve it?

I am trying to train a network with a leveldb dataset using brew.db_input to feed the input layer.
