### ISSUE TITLE
Ubuntu 14.04 server - libCaffe2_CPU.so missing

### ISSUE THREAD

**Issue by aaronmarkham** [facebookarchive/caffe2#99]
After setting up Ubuntu Trusty VM and getting the build process to succeed, I tried running the Basics tutorial notebook's first code block that imports the libraries, but was met with this error:

`WARNING:root:Debug message: libCaffe2_CPU.so: cannot open shared object file: No such file or directory
CRITICAL:root:Cannot load caffe2.python. Error: libCaffe2_CPU.so: cannot open shared object file: No such file or directory`

**Comment by slayton58** [comment]
Have you added the <install_root>/caffe2/python directory from the install path to your LD_LIBRARY_PATH?

**Comment by Yangqing** [comment]
Yeah, this is because the current cmake script is not properly set during the build process (it is only copied to caffe2/python when you do install). I am sending a PR soon to allow us to avoid the install stage - after that you should be able to put the build root to your PYTHONPATH and make things work.
